version: '3.8'
services:
  ai-services:
    build: ./scripts
    container_name: agency-ai-services
    ports:
      - "5001:5001"  # risk model
      - "5002:5002"  # note type NLP
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agency-backend
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - ai-services
    environment:
      - AI_RISK_URL=http://ai-services:5001/predict-risk
      - AI_NLP_URL=http://ai-services:5002/predict-note-type
    restart: unless-stopped 